### Site metadata

title: KISAMA
description: A gallery of images for an artist's portfolio, built with Jekyll

url: "https://kisama.netlify.app"
baseurl: ""

github_username: "Kisama-Kuki"
repository: "Kisama-Kuki/kisama.github.io"

google_analytics_key: ""

# For SEO tag.
logo: /siteicon.png
author:
  name: Michael Currin
  twitter:
social:
  name: KISAMA
  links:
    - https://github.com/Kisama-Kuki/kisama.github.io

### Build settings

timezone: Etc/UTC

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      text_width: true
  - scope:
      path: "index.html"
    values:
      text_width: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md
  - LICENSE
  - LICENCE-source
  - Makefile
  - netlify.toml
